config/routes.rb
Microgames::Application.routes.draw do

   match "/", :to => 'session#new', :as => :signin
   post "/sessions", :to => "session#create"
   match "/destroysession", :to => "session#destroy", :as => :signout

   match "/signup",  :to => "users#new"
   match "/users/:id", :to => "users#show", :as => :showuser
   match "/users/:id/profile", :to => "users#view_profile", :as => :viewprofile

   match "/creategame", :to => "games#new", :as => :create_game
   post "/games", :to => "games#create"
   match "/showgame/:id", :to => "games#show", :as => :show_game
   match "/changegame/:game_id/:state_index", :to => "games#change_state", :as => :change_state

end

app/models/game.rb
class Game < ActiveRecord::Base
	attr_accessible :type, :turn, :last_turn, :game_state

	#map to users via games_user
	has_many :games_users, :dependent => :destroy
	has_many :users, :through => :games_users

end

app/models/games_user.rb
class GamesUser < ActiveRecord::Base
  attr_accessible :game_id, :user_id
  belongs_to :user
  belongs_to :game
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :email, :password

  #map for games_users
  has_many :games_users
  has_many :games, :through => :games_users

  def self.find_friends(user_id)

  	friends = User.find(:all,
  						:conditions => ['id != (?)', user_id])

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

	def new
		@game = Game.new
		@friends = User.find_friends(session[:user_id])
		respond_to do |format|
			format.html #new.html.erb
			format.json { render :json => @game}
		end
	end

	def create
		#Set entry vaues 
		@game = Game.new
		@game.gametype = 1
		@game.turn = 1 #set turn to first player_number
		@game.last_turn = Time.now
		@game.game_state = '000000000'

		player_ids = Array.new
		player_ids.push(session[:user_id])

		params.each do |cur_param|
			if cur_param[0].starts_with? 'friend'
				player_ids.push(cur_param[0].split('.')[1])
			end
		end

		if @game.save
		#eventually change to association based entity creation
			GameLogic.create_games_users(player_ids, @game.id)
		else
		#error
		end

		respond_to do |format|
			if @game.id
		    	format.html { redirect_to showuser_path(session[:user_id]), :notice => 'Game was successfully created.' }
		    	format.json { render :json => @game, :status => :created}
		  	else
		    	format.html { render :action => "new" }
		    	format.json { render :json => @user.errors, :status => :unprocessable_entity }
		  	end
		end

	end

	def show
		@game = Game.find_by_id(params[:id])

		@curPN = GameLogic.get_player_number(@game.id, session[:user_id])

		#get hash of cell_states (X, O, Empty)
		@cellStates = Hash.new
		for i in 0..8
			@cellStates[i] = TicLogic.get_cell_owner(@game.game_state.split('')[i], @game, @curPN.to_i)
		end

		respond_to do |format|
      		format.html # show.html.erb
      		format.json { render :json => @user }
    	end
	end

	def change_state
		
		game = Game.find_by_id(params[:game_id])

		if(game.gametype == 1)
			game = TicLogic.change_state(params[:state_index], params[:game_id], session[:user_id])
		end

		redirect_to :action => "show", :id => game.id
	end

end

app/controllers/lobby_controller.rb
class LobbyController < ApplicationController
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

	def new
		render 'session/new'
	end

	def create
		user = User.find_by_email(params[:session][:email])
		if user && user.password == params[:session][:password] 
			session[:user_id] = user.id
			redirect_to showuser_path(session[:user_id])
		else
			flash.now[:error] = 'Invalid login information'
			redirect_to "/"
		end

		#else
		#	flash.now[:error] = 'Invalid email/password combination'
		#	render 'new'
		#end
	end

	def destroy
		session[:user_id] = nil
		puts "--------------------------------------------------------"
		puts "SESSION ID"
		puts session[:user_id]
		redirect_to signin_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
		respond_to do |format|
			format.html #new.html.erb
			format.json { render :json => @user}
		end
	end

	def create
		@user = User.new(params[:user])

		respond_to do |format|
		  if @user.save
		    session[:user_id] = @user.id
		    format.html { redirect_to showuser_path(@user.id), :notice => 'User was successfully created.' }
		    format.json { render :json => @user, :status => :created, :location => @user }
		  else
		    format.html { render :action => "new" }
		    format.json { render :json => @user.errors, :status => :unprocessable_entity }
		  end
		end
	end

	def show

		@user = User.find(params[:id])
		@friends = User.find_friends(params[:id])
		@usersGames = GameLogic.find_users_games(params[:id])
		@usersPlayerNumbers = Hash.new

		@usersGames.each do |ug|
			temp = GameLogic.get_player_number(ug.id, params[:id])
			@usersPlayerNumbers[ug.id] = temp
		end


	    respond_to do |format|
	      format.html # show.html.erb
	      format.json { render :json => @user }
	    end
  	end

  	def view_profile
  		@user = User.find(params[:id])
  		@games = GameLogic.find_ended_games(params[:id])
  		@numwins = 0
  		@numlosses = 0
  		@numdraws = 0

  		@games.each do |g|
  			if g.winner.to_i == @user.id.to_i
  				@numwins = @numwins + 1
  			else
  				@numlosses = @numlosses + 1
  			end
  		end

  		respond_to do |format|
	      format.html 
	      format.json { render :json => @user }
	    end

  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/lobby_helper.rb
module LobbyHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/new.html.erb
<h1>Create Game</h1>

<b>New Game Options</b>
<%= form_for :game, :url => {:action => :create } do |f| %>
	<%= f.label :game_type%>
	<%= f.select :gametype, options_for_select([["Tic Tac Toe", "1"], ["The Shining", "2"]]), :placeholder=>"Required" %>
	</br></br>
	<%= f.label :players%>
	</br>
	<% @friends.each do |friend| %>
	<%= check_box_tag 'friend.' + friend.id.to_s %><%= " " + friend.first_name + " " + friend.last_name %></br>
	<% end %>
</br>
<button type='submit' name='commit'>Create Game</button>
<% end %>

app/views/games/show.html.erb
<div align="center"><h1><%= GameLogic.get_game_name(@game.gametype.to_s) + " " + "Session:" + @game.id.to_s %> </h1></div>
<% if @game.winner.to_i >  0 %>
	<h2><font color="red" >PLAYER <%= @game.winner %> has won!</font></h2>
	</br>
	<%= link_to "Leave Game", showuser_path(session[:user_id]) %>
<% end %>

<!--For now, this is hardcoded for tic-tac-toe.  But we can put into partial templates that will render depending on value of @game.gametype.to_s when we have more games-->
<table align="center" border='1'>
	<% tr_start = [0, 3, 6] %>
	<% tr_end = [2, 5, 8] %>
	<% for i in 0..8 %>
	<% if tr_start.include? i %>
	<tr>
	<% end %>
			<td width=50 height=50 align="center">
				<% if @cellStates[i] == 'X' or @cellStates[i] == 'O' %>
					<%= @cellStates[i] %>
				<% else %>
					<% if @game.turn == @curPN.to_i %>
						<%= link_to @cellStates[i], change_state_path(@game.id, i), {:class => "tttgrid"}%>
					<% else %>
						<%= @cellStates[i] %>
					<% end %>
				<% end %>
			</td>
	<% if tr_end.include? i %>
	</tr>
	<% end %>
	<% end %>
</table>

app/views/layouts/_header.html.erb
<div id="header">
	<% if session[:user_id] != nil %> <%= link_to "Home", showuser_path(session[:user_id]), {:class => "mglink"} %> <% else %> <%= link_to "Home", signin_path, {:class => "mglink"} %> <% end %>  <%= link_to "Sign Out", signout_path, {:class => "mglink"} %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Microgames</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render :partial => "layouts/header" %>
<%= yield %>

</body>
</html>

app/views/session/new.html.erb
<h1>Welcome to the Website!</h1>

<h1>Sign in</h1>

<%=form_for :session, :url => sessions_path do |f| %>

	<%= f.label :email %>
	<%= f.text_field :email %>

	<%= f.label :password %>
	<%= f.password_field :password %>

	<%= f.submit "Sign in" %>
<% end %>

<p>Or...<%= link_to "Sign up!", signup_path %></p>

app/views/users/show.html.erb
<% if params[:id].to_i == session[:user_id].to_i %>
	<p id="notice"><%= notice %></p>
	<h1><b>WELCOME TO YOUR HOME PAGE <%= @user.first_name %>!</b></h1>
	<p>
		<%= link_to "Create Game", create_game_path, {:class => "mglink"} %>
		<%= link_to "View My Profile", viewprofile_path(@user.id), {:class => "mglink"} %>

	<p>
		<b>Friends</b>
		</br>
		<!--this is all users for now...set up friends lists relationships later-->
		<% @friends.each do |friend| %>
			<%= link_to friend.first_name + " " + friend.last_name, showuser_path(friend.id), {:class => "mglink"} %>
			<br>
		<% end %>
	</p>

	<p>
		<b>Current Games</b>
		</br>
		<% index = 0 %>
		<% @usersGames.each do |g| %>
			<% if g.winner.to_i == 0 %>
				Game ID: <%= link_to g.id, show_game_path(g.id), {:class => "mglink"} %>
				<% if @usersPlayerNumbers[g.id] == g.turn.to_s and g.winner.to_i == 0%>
					<font color="green">(Your Turn!)</font>
				<% end %>
			</br>
			<% end %>
			<% index = index + 1 %>
		<% end %>
		</br>
<% else %>
	<p id="notice"><%= notice %></p>
	<h1><b><%= @user.first_name %>'s Page</b></h1>
	<p>
		<%= link_to "View Profile", viewprofile_path(@user.id), {:class => "mglink"} %>
	<p>
		<b>Friends</b>
		</br>
		<!--this is all users for now...set up friends lists relationships later-->
		<% @friends.each do |friend| %>
			<%= link_to friend.first_name + " " + friend.last_name, showuser_path(friend.id), {:class => "mglink"}  %>
			<br>
		<% end %>
	</p>

	<p>
		<b>Current Games</b>
		</br>
		<% index = 0 %>
		<% @usersGames.each do |g| %>
			<% if g.winner.to_i == 0 %>
				Game ID: <%= link_to g.id, show_game_path(g.id), {:class => "mglink"} %>
			</br>
			<% end %>
			<% index = index + 1 %>
		<% end %>
		</br>
<% end %>

app/views/users/view_profile.html.erb
<h1>Gamer Profile</h1>
<p><b><%= @user.first_name %> <%= @user.last_name %></b></p>
<p>
	<div>W/L/<%= @numwins %>:<%= @numlosses %></div>
</p>
<table>
	<tr>
		<td>Game ID</td>
		<td>Result</td>
		<td>Ended</td>
	</tr>
	<% @games.each do |g| %>
		<tr>
			<td><%= g.id %></td>
			<td><% if g.winner.to_i == @user.id.to_i %><font color="green">Won</font><% else %><font color="red">Lost</font><% end %></td>
			<td><%= g.last_turn %></td>
		</tr>
	<% end %>
</table>